logging:
  level:
    root: INFO
server:
  port: 8443
spring:
  application:
    name: wj-java
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:learn_language
    username: root
    password: 190627

  data:
    redis:
      host: localhost
      client-type: lettuce

mybatis-plus:

  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl